spring:
  #启用不同环境的配置文件
  profiles:
    active: core,db,api
  #设置上传的文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
#-----------------------------------------------------------------------------------------------




# 日志输出格式：
# %d表示日期时间，
# %thread表示线程名，
# %-5level：级别从左显示5个字符宽度
# %logger{50} 表示logger名字最长50个字符，否则按照句点分割。
# %msg：日志消息，
# %n是换行符

#设置日志输出格式
#logging:
#  pattern:
#    console: Time:%d{yyyy-MM-dd HH:mm:ss.SSS} -- thread:[%thread] -- level:[%-5level] -- %logger{20} - %msg%n
#-----------------------------------------------------------------------------------------------