#数据库连接信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://121.4.66.115:3306/lymall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    #redis 地址
    host: 121.4.66.115
    # 连接超时时间（毫秒）
    timeout: 10000
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 1024
        # 连接池最大阻塞等待时间（毫秒）（使用负值表示没有限制）
        max-wait: 100000

#-----------------------------------------------------------------------------------------------

#分页插件配置
pagehelper:
  #分页插件 数据库方言
  helper-dialect: mysql
  #参数
  params: count=countSql
  #合理化分页
  reasonable: true
  #支持方法参数
  support-methods-arguments: true

#-----------------------------------------------------------------------------------------------

#mybatis配置
mybatis:
  configuration:
    #开启驼峰命名支持
    map-underscore-to-camel-case: true
    #开启缓存
    cache-enabled: true

#-----------------------------------------------------------------------------------------------